"""Added account table

Revision ID: 9bc82f680af1
Revises: 
Create Date: 2023-07-22 20:54:18.679131

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9bc82f680af1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', mysql.INTEGER(display_width=11),
                              autoincrement=True, nullable=False),
                    sa.Column('username', mysql.VARCHAR(
                        length=100), nullable=False),
                    sa.Column('password', mysql.VARCHAR(
                        length=250), nullable=False),
                    sa.Column('name', mysql.VARCHAR(
                        length=250), nullable=False),
                    sa.Column('role', mysql.ENUM(
                        'ADMIN', 'MAHASISWA'), nullable=False),
                    sa.Column('flag', mysql.INTEGER(display_width=11), server_default=sa.text(
                        "'1'"), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_default_charset='latin1',
                    mysql_engine='InnoDB'
                    )
    op.create_table('kelas',
                    sa.Column('id', mysql.INTEGER(display_width=11),
                              autoincrement=True, nullable=False),
                    sa.Column('fakultas', mysql.VARCHAR(
                        length=250), nullable=False),
                    sa.Column('prodi', mysql.VARCHAR(
                        length=250), nullable=False),
                    sa.Column('kelas', mysql.VARCHAR(
                        length=250), nullable=False),
                    sa.Column('flag', mysql.INTEGER(display_width=11), server_default=sa.text(
                        "'1'"), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_default_charset='latin1',
                    mysql_engine='InnoDB'
                    )
    op.create_table('kelas_mhs',
                    sa.Column('id', mysql.INTEGER(display_width=11),
                              autoincrement=False, nullable=False),
                    sa.Column('kelas_id', mysql.INTEGER(
                        display_width=11), autoincrement=False, nullable=False),
                    sa.Column('mahasiswa_id', mysql.INTEGER(display_width=11),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(
                        ['kelas_id'], ['kelas.id'], name='kelas_mhs_ibfk_1'),
                    sa.ForeignKeyConstraint(
                        ['mahasiswa_id'], ['users.id'], name='kelas_mhs_ibfk_2'),
                    mysql_default_charset='latin1',
                    mysql_engine='InnoDB'
                    )
    op.create_table('user_training',
                    sa.Column('id', mysql.INTEGER(display_width=11),
                              autoincrement=True, nullable=False),
                    sa.Column('user_id', mysql.INTEGER(display_width=11),
                              autoincrement=False, nullable=False),
                    sa.Column('path', mysql.VARCHAR(
                        length=250), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], name='user_training_ibfk_1'),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_default_charset='latin1',
                    mysql_engine='InnoDB'
                    )
    op.create_table('mata_kuliah',
                    sa.Column('id', mysql.INTEGER(display_width=11),
                              autoincrement=True, nullable=False),
                    sa.Column('nama', mysql.VARCHAR(
                        length=250), nullable=False),
                    sa.Column('flag', mysql.INTEGER(display_width=11), server_default=sa.text(
                        "'1'"), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_default_charset='latin1',
                    mysql_engine='InnoDB'
                    )
    op.create_table('jadwal',
                    sa.Column('id', mysql.INTEGER(display_width=11),
                              autoincrement=True, nullable=False),
                    sa.Column('mata_kuliah_id', mysql.INTEGER(
                        display_width=11), autoincrement=False, nullable=False),
                    sa.Column('hari', mysql.ENUM('Senin', 'Selasa', 'Rabu',
                                                 'Kamis', 'Jumat', 'Sabtu', 'Minggu'), nullable=False),
                    sa.Column('jam_mulai', mysql.TIME(), nullable=False),
                    sa.Column('jam_selesai', mysql.INTEGER(display_width=11),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['mata_kuliah_id'], [
                        'mata_kuliah.id'], name='jadwal_ibfk_1'),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_default_charset='latin1',
                    mysql_engine='InnoDB'
                    )
    op.create_table('presensi',
                    sa.Column('id', mysql.INTEGER(display_width=11),
                              autoincrement=True, nullable=False),
                    sa.Column('user_id', mysql.INTEGER(display_width=11),
                              autoincrement=False, nullable=False),
                    sa.Column('kelas_id', mysql.INTEGER(display_width=11),
                              autoincrement=False, nullable=False),
                    sa.Column('jadwal_id', mysql.INTEGER(display_width=11),
                              autoincrement=False, nullable=False),
                    sa.Column('mata_kuliah_id', mysql.INTEGER(display_width=11),
                              autoincrement=False, nullable=False),
                    sa.Column('tanggal', sa.DATE(), nullable=False),
                    sa.Column('jam', mysql.TIME(), nullable=False),
                    sa.Column('photo', mysql.VARCHAR(
                        length=255), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['jadwal_id'], ['jadwal.id'], name='presensi_ibfk_3'),
                    sa.ForeignKeyConstraint(
                        ['kelas_id'], ['kelas.id'], name='presensi_ibfk_2'),
                    sa.ForeignKeyConstraint(['mata_kuliah_id'], [
                        'mata_kuliah.id'], name='presensi_ibfk_4'),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], name='presensi_ibfk_1'),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_default_charset='latin1',
                    mysql_engine='InnoDB'
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('presensi')
    op.drop_table('jadwal')
    op.drop_table('mata_kuliah')
    op.drop_table('user_training')
    op.drop_table('kelas_mhs')
    op.drop_table('kelas')
    op.drop_table('users')
    # ### end Alembic commands ###
